/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessTokens: () => import('#controllers/access_tokens_controller'),
  auth: {
    Session: () => import('#controllers/auth/session_controller'),
  },
  NewAccount: () => import('#controllers/new_account_controller'),
  pms: {
    Customer: () => import('#controllers/pms/customer_controller'),
    Destination: () => import('#controllers/pms/destination_controller'),
    DoAndDonts: () => import('#controllers/pms/do_and_donts_controller'),
    EmailTemplate: () => import('#controllers/pms/email_template_controller'),
    Itinerary: () => import('#controllers/pms/itinerary_controller'),
    Quotation: () => import('#controllers/pms/quotation_controller'),
    QuotationFeatur: () => import('#controllers/pms/quotation_featur_controller'),
    RoomType: () => import('#controllers/pms/room_type_controller'),
  },
  Profile: () => import('#controllers/profile_controller'),
}
