/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['abilities', 'createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class CustomerSchema extends BaseModel {
  static $columns = ['address', 'createdAt', 'email', 'id', 'name', 'phone', 'updatedAt'] as const
  $columns = CustomerSchema.$columns
  @column()
  declare address: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare phone: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DestinationSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'updatedAt'] as const
  $columns = DestinationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class DoAndDontSchema extends BaseModel {
  static $columns = ['content', 'createdAt', 'destinationId', 'id', 'type', 'updatedAt'] as const
  $columns = DoAndDontSchema.$columns
  @column()
  declare content: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare destinationId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class EmailTemplateSchema extends BaseModel {
  static $columns = ['body', 'createdAt', 'id', 'isActive', 'name', 'subject', 'updatedAt'] as const
  $columns = EmailTemplateSchema.$columns
  @column()
  declare body: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare isActive: boolean | null
  @column()
  declare name: string
  @column()
  declare subject: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ItinerarySchema extends BaseModel {
  static $columns = ['createdAt', 'days', 'destinationId', 'id', 'nights', 'overview', 'price', 'title', 'updatedAt'] as const
  $columns = ItinerarySchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare days: number
  @column()
  declare destinationId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare nights: number
  @column()
  declare overview: string | null
  @column()
  declare price: number | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class QuotationFeatureSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'featureName', 'id', 'quotationId', 'updatedAt'] as const
  $columns = QuotationFeatureSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare featureName: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare quotationId: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class QuotationSchema extends BaseModel {
  static $columns = ['createdAt', 'customerId', 'destinationId', 'id', 'itineraryId', 'notes', 'pdfPath', 'roomTypeId', 'status', 'totalPrice', 'updatedAt'] as const
  $columns = QuotationSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare customerId: string
  @column()
  declare destinationId: string
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare itineraryId: string
  @column()
  declare notes: string | null
  @column()
  declare pdfPath: string | null
  @column()
  declare roomTypeId: string
  @column()
  declare status: string
  @column()
  declare totalPrice: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class RoomTypeSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'itineraryId', 'maxPerson', 'name', 'price', 'updatedAt'] as const
  $columns = RoomTypeSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare itineraryId: string
  @column()
  declare maxPerson: number | null
  @column()
  declare name: string
  @column()
  declare price: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class UserSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'fullName', 'id', 'password', 'updatedAt'] as const
  $columns = UserSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare password: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
