/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type CustomerTransformer from '#transformers/customer_transformer'
import type DestinationTransformer from '#transformers/destination_transformer'
import type DoAndDontsTransformer from '#transformers/do_and_donts_transformer'
import type EmailTemplateTransformer from '#transformers/email_template_transformer'
import type ItineraryTransformer from '#transformers/itinerary_transformer'
import type QuotationFeatureTransformer from '#transformers/quotation_feature_transformer'
import type QuotationTransformer from '#transformers/quotation_transformer'
import type RoomTypeTransformer from '#transformers/room_type_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Customer = InferData<CustomerTransformer>
  export namespace Customer {
    export type Variants = InferVariants<CustomerTransformer>
  }
  export type Destination = InferData<DestinationTransformer>
  export namespace Destination {
    export type Variants = InferVariants<DestinationTransformer>
  }
  export type DoAndDonts = InferData<DoAndDontsTransformer>
  export namespace DoAndDonts {
    export type Variants = InferVariants<DoAndDontsTransformer>
  }
  export type EmailTemplate = InferData<EmailTemplateTransformer>
  export namespace EmailTemplate {
    export type Variants = InferVariants<EmailTemplateTransformer>
  }
  export type Itinerary = InferData<ItineraryTransformer>
  export namespace Itinerary {
    export type Variants = InferVariants<ItineraryTransformer>
  }
  export type QuotationFeature = InferData<QuotationFeatureTransformer>
  export namespace QuotationFeature {
    export type Variants = InferVariants<QuotationFeatureTransformer>
  }
  export type Quotation = InferData<QuotationTransformer>
  export namespace Quotation {
    export type Variants = InferVariants<QuotationTransformer>
  }
  export type RoomType = InferData<RoomTypeTransformer>
  export namespace RoomType {
    export type Variants = InferVariants<RoomTypeTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
