/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedToursRouteImport } from './routes/_authenticated/tours'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedItinerariesRouteImport } from './routes/_authenticated/itineraries'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors429RouteImport } from './routes/(errors)/429'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors400RouteImport } from './routes/(errors)/400'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ApiRemindersPushSubscriptionRouteImport } from './routes/api/reminders/push-subscription'
import { Route as ApiRemindersPushRouteImport } from './routes/api/reminders/push'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedToursTourIdRouteImport } from './routes/_authenticated/tours_.$tourId'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated/clients_.$clientId'
import { Route as AuthenticatedBookingsAttendeeIdVouchersRouteImport } from './routes/_authenticated/bookings_.$attendeeId.vouchers'
import { Route as AuthenticatedBookingsAttendeeIdReceiptsRouteImport } from './routes/_authenticated/bookings_.$attendeeId.receipts'

const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedToursRoute = AuthenticatedToursRouteImport.update({
  id: '/tours',
  path: '/tours',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedItinerariesRoute =
  AuthenticatedItinerariesRouteImport.update({
    id: '/itineraries',
    path: '/itineraries',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors429Route = errors429RouteImport.update({
  id: '/(errors)/429',
  path: '/429',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors400Route = errors400RouteImport.update({
  id: '/(errors)/400',
  path: '/400',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRemindersPushSubscriptionRoute =
  ApiRemindersPushSubscriptionRouteImport.update({
    id: '/api/reminders/push-subscription',
    path: '/api/reminders/push-subscription',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiRemindersPushRoute = ApiRemindersPushRouteImport.update({
  id: '/api/reminders/push',
  path: '/api/reminders/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedToursTourIdRoute =
  AuthenticatedToursTourIdRouteImport.update({
    id: '/tours_/$tourId',
    path: '/tours/$tourId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/clients_/$clientId',
    path: '/clients/$clientId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsAttendeeIdVouchersRoute =
  AuthenticatedBookingsAttendeeIdVouchersRouteImport.update({
    id: '/bookings_/$attendeeId/vouchers',
    path: '/bookings/$attendeeId/vouchers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsAttendeeIdReceiptsRoute =
  AuthenticatedBookingsAttendeeIdReceiptsRouteImport.update({
    id: '/bookings_/$attendeeId/receipts',
    path: '/bookings/$attendeeId/receipts',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/offline': typeof OfflineRoute
  '/login': typeof authLoginRoute
  '/400': typeof errors400Route
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/429': typeof errors429Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/clients': typeof AuthenticatedClientsRoute
  '/itineraries': typeof AuthenticatedItinerariesRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tours': typeof AuthenticatedToursRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/tours/$tourId': typeof AuthenticatedToursTourIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/reminders/push': typeof ApiRemindersPushRoute
  '/api/reminders/push-subscription': typeof ApiRemindersPushSubscriptionRoute
  '/bookings/$attendeeId/receipts': typeof AuthenticatedBookingsAttendeeIdReceiptsRoute
  '/bookings/$attendeeId/vouchers': typeof AuthenticatedBookingsAttendeeIdVouchersRoute
}
export interface FileRoutesByTo {
  '/offline': typeof OfflineRoute
  '/login': typeof authLoginRoute
  '/400': typeof errors400Route
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/429': typeof errors429Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/clients': typeof AuthenticatedClientsRoute
  '/itineraries': typeof AuthenticatedItinerariesRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tours': typeof AuthenticatedToursRoute
  '/': typeof AuthenticatedIndexRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/tours/$tourId': typeof AuthenticatedToursTourIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/reminders/push': typeof ApiRemindersPushRoute
  '/api/reminders/push-subscription': typeof ApiRemindersPushSubscriptionRoute
  '/bookings/$attendeeId/receipts': typeof AuthenticatedBookingsAttendeeIdReceiptsRoute
  '/bookings/$attendeeId/vouchers': typeof AuthenticatedBookingsAttendeeIdVouchersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/offline': typeof OfflineRoute
  '/(auth)/login': typeof authLoginRoute
  '/(errors)/400': typeof errors400Route
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/429': typeof errors429Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/itineraries': typeof AuthenticatedItinerariesRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tours': typeof AuthenticatedToursRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clients_/$clientId': typeof AuthenticatedClientsClientIdRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/tours_/$tourId': typeof AuthenticatedToursTourIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/reminders/push': typeof ApiRemindersPushRoute
  '/api/reminders/push-subscription': typeof ApiRemindersPushSubscriptionRoute
  '/_authenticated/bookings_/$attendeeId/receipts': typeof AuthenticatedBookingsAttendeeIdReceiptsRoute
  '/_authenticated/bookings_/$attendeeId/vouchers': typeof AuthenticatedBookingsAttendeeIdVouchersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/offline'
    | '/login'
    | '/400'
    | '/401'
    | '/403'
    | '/404'
    | '/429'
    | '/500'
    | '/503'
    | '/clients'
    | '/itineraries'
    | '/reminders'
    | '/settings'
    | '/tours'
    | '/clients/$clientId'
    | '/errors/$error'
    | '/tours/$tourId'
    | '/api/auth/$'
    | '/api/reminders/push'
    | '/api/reminders/push-subscription'
    | '/bookings/$attendeeId/receipts'
    | '/bookings/$attendeeId/vouchers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/offline'
    | '/login'
    | '/400'
    | '/401'
    | '/403'
    | '/404'
    | '/429'
    | '/500'
    | '/503'
    | '/clients'
    | '/itineraries'
    | '/reminders'
    | '/settings'
    | '/tours'
    | '/'
    | '/clients/$clientId'
    | '/errors/$error'
    | '/tours/$tourId'
    | '/api/auth/$'
    | '/api/reminders/push'
    | '/api/reminders/push-subscription'
    | '/bookings/$attendeeId/receipts'
    | '/bookings/$attendeeId/vouchers'
  id:
    | '__root__'
    | '/_authenticated'
    | '/offline'
    | '/(auth)/login'
    | '/(errors)/400'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/429'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/clients'
    | '/_authenticated/itineraries'
    | '/_authenticated/reminders'
    | '/_authenticated/settings'
    | '/_authenticated/tours'
    | '/_authenticated/'
    | '/_authenticated/clients_/$clientId'
    | '/_authenticated/errors/$error'
    | '/_authenticated/tours_/$tourId'
    | '/api/auth/$'
    | '/api/reminders/push'
    | '/api/reminders/push-subscription'
    | '/_authenticated/bookings_/$attendeeId/receipts'
    | '/_authenticated/bookings_/$attendeeId/vouchers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  OfflineRoute: typeof OfflineRoute
  authLoginRoute: typeof authLoginRoute
  errors400Route: typeof errors400Route
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors429Route: typeof errors429Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRemindersPushRoute: typeof ApiRemindersPushRoute
  ApiRemindersPushSubscriptionRoute: typeof ApiRemindersPushSubscriptionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tours': {
      id: '/_authenticated/tours'
      path: '/tours'
      fullPath: '/tours'
      preLoaderRoute: typeof AuthenticatedToursRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/itineraries': {
      id: '/_authenticated/itineraries'
      path: '/itineraries'
      fullPath: '/itineraries'
      preLoaderRoute: typeof AuthenticatedItinerariesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/429': {
      id: '/(errors)/429'
      path: '/429'
      fullPath: '/429'
      preLoaderRoute: typeof errors429RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/400': {
      id: '/(errors)/400'
      path: '/400'
      fullPath: '/400'
      preLoaderRoute: typeof errors400RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reminders/push-subscription': {
      id: '/api/reminders/push-subscription'
      path: '/api/reminders/push-subscription'
      fullPath: '/api/reminders/push-subscription'
      preLoaderRoute: typeof ApiRemindersPushSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reminders/push': {
      id: '/api/reminders/push'
      path: '/api/reminders/push'
      fullPath: '/api/reminders/push'
      preLoaderRoute: typeof ApiRemindersPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tours_/$tourId': {
      id: '/_authenticated/tours_/$tourId'
      path: '/tours/$tourId'
      fullPath: '/tours/$tourId'
      preLoaderRoute: typeof AuthenticatedToursTourIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients_/$clientId': {
      id: '/_authenticated/clients_/$clientId'
      path: '/clients/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings_/$attendeeId/vouchers': {
      id: '/_authenticated/bookings_/$attendeeId/vouchers'
      path: '/bookings/$attendeeId/vouchers'
      fullPath: '/bookings/$attendeeId/vouchers'
      preLoaderRoute: typeof AuthenticatedBookingsAttendeeIdVouchersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings_/$attendeeId/receipts': {
      id: '/_authenticated/bookings_/$attendeeId/receipts'
      path: '/bookings/$attendeeId/receipts'
      fullPath: '/bookings/$attendeeId/receipts'
      preLoaderRoute: typeof AuthenticatedBookingsAttendeeIdReceiptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedItinerariesRoute: typeof AuthenticatedItinerariesRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedToursRoute: typeof AuthenticatedToursRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedToursTourIdRoute: typeof AuthenticatedToursTourIdRoute
  AuthenticatedBookingsAttendeeIdReceiptsRoute: typeof AuthenticatedBookingsAttendeeIdReceiptsRoute
  AuthenticatedBookingsAttendeeIdVouchersRoute: typeof AuthenticatedBookingsAttendeeIdVouchersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedItinerariesRoute: AuthenticatedItinerariesRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedToursRoute: AuthenticatedToursRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientsClientIdRoute: AuthenticatedClientsClientIdRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedToursTourIdRoute: AuthenticatedToursTourIdRoute,
  AuthenticatedBookingsAttendeeIdReceiptsRoute:
    AuthenticatedBookingsAttendeeIdReceiptsRoute,
  AuthenticatedBookingsAttendeeIdVouchersRoute:
    AuthenticatedBookingsAttendeeIdVouchersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  OfflineRoute: OfflineRoute,
  authLoginRoute: authLoginRoute,
  errors400Route: errors400Route,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors429Route: errors429Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRemindersPushRoute: ApiRemindersPushRoute,
  ApiRemindersPushSubscriptionRoute: ApiRemindersPushSubscriptionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
